// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkrlzqdekymqdjspwgul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrcmx6cWRla3ltcWRqc3B3Z3VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjYxMjUsImV4cCI6MjA2NjAwMjEyNX0.tr27EUktiMpyIwTMRrY9sVeFCo0aAL6ks2mAad4sORs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);